init:
	curl http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.js -o prettify.js
	curl http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.css -o prettify.css

.PHONY: init
